name: Compile release general kernel

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: "Select kernel version"
        required: false
        default: "5.15.162"
        type: string
      kernel_auto:
        description: "Auto use the latest kernel"
        required: false
        default: false
        type: boolean
      kernel_package:
        description: "Select compile package list"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - dtbs
      kernel_toolchain:
        description: "Select the compilation toolchain"
        required: false
        default: "gcc"
        type: choice
        options:
          - clang
          - gcc
          - gcc-11.3
          - gcc-12.2
          - gcc-12.3
          - gcc-13.2
          - gcc-13.3
      compress_format:
        description: "Set the initrd compression format"
        required: false
        default: "xz"
        type: choice
        options:
          - xz
          - gzip
          - zstd
          - lzma
      kernel_sign:
        description: "Set the kernel custom signature"
        required: false
        default: "-1-7d9483ff60109a7caf36266e8917014e"
        type: string
      kernel_config:
        description: "Set the path of kernel .config"
        required: false
        default: "kernel-config/release/general"
        type: string

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install $(curl -fsSL https://is.gd/depend_ubuntu2204_armbian)
          sudo timedatectl set-timezone "${TZ}"

      - name: Debug - Show directory contents
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Action directory contents:"
          ls -la ${{ github.action_path }}

      - name: Compile Kernel
        uses: kemp-zz/amlogic-s9xxx-armbian@main
        with:
          build_target: kernel
          kernel_version: ${{ github.event.inputs.kernel_version || '5.15.162' }}
          kernel_auto: false
          kernel_package: ${{ github.event.inputs.kernel_package || 'all' }}
          kernel_toolchain: ${{ github.event.inputs.kernel_toolchain || 'gcc' }}
          kernel_sign: ${{ github.event.inputs.kernel_sign || '-1-7d9483ff60109a7caf36266e8917014e' }}
          kernel_config: ${{ github.event.inputs.kernel_config || 'kernel-config/release/general' }}
          compress_format: ${{ github.event.inputs.compress_format || 'xz' }}

      - name: Check Compilation Results
        if: always()
        run: |
          echo "Checking compilation results..."
          
          # Check if the output directory exists
          if [ -d "/home/runner/work/_actions/kemp-zz/amlogic-s9xxx-armbian/main/compile-kernel/output" ]; then
            echo "Output directory exists."
            
            # List contents of the output directory
            echo "Contents of output directory:"
            ls -R /home/runner/work/_actions/kemp-zz/amlogic-s9xxx-armbian/main/compile-kernel/output
            
            # Check for kernel modules and their versions
            echo "Checking kernel module versions:"
            find /home/runner/work/_actions/kemp-zz/amlogic-s9xxx-armbian/main/compile-kernel/output -name "*.ko" | xargs modinfo | grep -E "^version:" | sort | uniq
          else
            echo "Error: Output directory not found."
          fi
          
          # Check disk usage
          echo "Disk usage after compilation:"
          df -h
      - name: Upload Kernel to Release
        uses: ncipollo/release-action@main
        if: env.PACKAGED_STATUS == 'success' && !cancelled()
        with:
          tag: kernel_${{ github.event.inputs.kernel_version || '5.15.162' }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Notification of build failure
        if: failure()
        run: |
          echo "The kernel compilation process has failed."
          echo "GitHub Action Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          exit 1
