name: Compile release general kernel

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: "Select kernel version"
        required: false
        default: "5.15.162"
        type: string
      kernel_auto:
        description: "Auto use the latest kernel"
        required: false
        default: false
        type: boolean
      kernel_package:
        description: "Select compile package list"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - dtbs
      kernel_toolchain:
        description: "Select the compilation toolchain"
        required: false
        default: "gcc"
        type: choice
        options:
          - clang
          - gcc
          - gcc-11.3
          - gcc-12.2
          - gcc-12.3
          - gcc-13.2
          - gcc-13.3
      kernel_sign:
        description: "Set the kernel custom signature"
        required: false
        default: "-1-7d9483ff60109a7caf36266e8917014e"
        type: string
      kernel_config:
        description: "Set the path of kernel .config"
        required: false
        default: "kernel-config/release/general"
        type: string
      compress_format:
        description: "Set the initrd compression format"
        required: false
        default: "xz"
        type: choice
        options:
          - xz
          - gzip
          - zstd
          - lzma

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install $(curl -fsSL https://is.gd/depend_ubuntu2204_armbian)
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Clone kernel source
        run: |
          git clone --depth 1 https://github.com/unifreq/linux-5.15.y.git -b main kernel-source
          cd kernel-source
          git fetch --depth=1 origin 244dce52c74abd24de772a07f83522493c888412
          git checkout FETCH_HEAD

      - name: Verify kernel version
        run: |
          cd kernel-source
          echo "Checking kernel version..."
          make kernelversion
          grep -E "^VERSION|^PATCHLEVEL|^SUBLEVEL|^EXTRAVERSION" Makefile
          git log -1 --oneline
          if [[ $(make kernelversion) != "${{ github.event.inputs.kernel_version }}" ]]; then
            echo "Error: Kernel version mismatch. Expected ${{ github.event.inputs.kernel_version }}, but got $(make kernelversion)"
            exit 1
          fi

      - name: Compile Kernel
        if: success()
        uses: kemp-zz/amlogic-s9xxx-armbian@main
        with:
          build_target: kernel
          kernel_version: ${{ github.event.inputs.kernel_version }}
          kernel_auto: ${{ github.event.inputs.kernel_auto }}
          kernel_package: ${{ github.event.inputs.kernel_package }}
          kernel_toolchain: ${{ github.event.inputs.kernel_toolchain }}
          kernel_sign: ${{ github.event.inputs.kernel_sign }}
          kernel_config: ${{ github.event.inputs.kernel_config }}
          compress_format: ${{ github.event.inputs.compress_format }}

      - name: Upload Kernel to Release
        if: ${{ env.PACKAGED_STATUS == 'success' && !cancelled() }}
        uses: ncipollo/release-action@main
        with:
          tag: kernel_${{ github.event.inputs.kernel_version }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Notification of build failure
        if: failure()
        run: |
          echo "The kernel compilation process has failed."
          echo "GitHub Action Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          exit 1
