name: Compile release general kernel

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      kernel_source:
        description: "Select the kernel source"
        required: false
        default: "unifreq"
        type: choice
        options:
          - unifreq
          - codesnas
      kernel_version:
        description: "Select kernel version"
        required: false
        default: "5.15.162"
        type: string
      kernel_auto:
        description: "Auto use the latest kernel"
        required: false
        default: false
        type: boolean
      kernel_package:
        description: "Select compile package list"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - dtbs
      kernel_toolchain:
        description: "Select the compilation toolchain"
        required: false
        default: "gcc"
        type: choice
        options:
          - clang
          - gcc
          - gcc-11.3
          - gcc-12.2
          - gcc-12.3
          - gcc-13.2
          - gcc-13.3
      compress_format:
        description: "Set the initrd compression format"
        required: false
        default: "xz"
        type: choice
        options:
          - xz
          - gzip
          - zstd
          - lzma
      kernel_sign:
        description: "Set the kernel custom signature"
        required: false
        default: "-ophub"
        type: choice
        options:
          - -ophub
          - -happy-new-year
          - -dragon-boat-festival
          - -mid-autumn-festival
          - -happy-national-day
          - -merry-christmas
          - -spring-plowing
          - -summer-growing
          - -autumn-harvesting
          - -winter-storing
          - -1-7d9483ff60109a7caf36266e8917014e
      kernel_config:
        description: "Set the path of kernel .config"
        required: false
        default: "kernel-config/release/general"
        type: choice
        options:
          - kernel-config/release/general
          - false

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install $(curl -fsSL https://is.gd/depend_ubuntu2204_armbian)
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.kernel_source || 'unifreq' }}/linux-5.15.y
          ref: ${{ github.event.inputs.kernel_version == '5.15.162' && '244dce52c74abd24de772a07f83522493c888412' || '' }}
          path: kernel-source

      - name: Update Makefile version
        working-directory: kernel-source
        run: |
          echo "Current directory: $(pwd)"
          echo "Makefile content before modification:"
          cat Makefile | grep -E '^(VERSION|PATCHLEVEL|SUBLEVEL|EXTRAVERSION) ='
          
          sed -i 's/^SUBLEVEL = .*/SUBLEVEL = 162/' Makefile
          
          echo "Makefile content after modification:"
          cat Makefile | grep -E '^(VERSION|PATCHLEVEL|SUBLEVEL|EXTRAVERSION) ='
          
          if ! grep -q '^SUBLEVEL = 162' Makefile; then
            echo "Failed to update SUBLEVEL in Makefile"
            exit 1
          fi
          
          if ! grep -q '^EXTRAVERSION =' Makefile; then
            echo "EXTRAVERSION not found, adding it..."
            echo "EXTRAVERSION =" >> Makefile
          fi
          
          echo "Final Makefile content:"
          cat Makefile | grep -E '^(VERSION|PATCHLEVEL|SUBLEVEL|EXTRAVERSION) ='

      - name: Compile the kernel
        uses: kemp-zz/amlogic-s9xxx-armbian@main
        with:
          build_target: kernel
          kernel_source: kernel-source
          kernel_version: ${{ github.event.inputs.kernel_version || '5.15.162' }}
          kernel_auto: ${{ github.event.inputs.kernel_auto }}
          kernel_package: ${{ github.event.inputs.kernel_package || 'all' }}
          kernel_toolchain: ${{ github.event.inputs.kernel_toolchain || 'gcc' }}
          kernel_sign: ${{ github.event.inputs.kernel_sign || '-ophub' }}
          kernel_config: ${{ github.event.inputs.kernel_config || 'kernel-config/release/general' }}
          compress_format: ${{ github.event.inputs.compress_format || 'xz' }}

      - name: Upload Kernel to Release
        if: env.PACKAGED_STATUS == 'success' && !cancelled()
        uses: ncipollo/release-action@main
        with:
          tag: kernel_${{ github.event.inputs.kernel_version || '5.15.162' }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Notification of build failure
        if: failure()
        run: |
          echo "The kernel compilation process has failed."
          exit 1
