name: test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Select the release version according to Packages.manifest"
        required: true
      md5:
        description: "MD5 checksum for verification"
        required: true

env:
  TZ: America/New_York

jobs:
  get-manifest-data:
    runs-on: ubuntu-latest
    outputs:
      kernel_version: ${{ steps.set-env.outputs.kernel_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read Packages.manifest
        id: read_manifest
        run: |
          jq -r '.kernel_version' Packages.manifest
          kernel_version=$(jq -r '.kernel_version' Packages.manifest)
          echo "::set-output name=kernel_version::$kernel_version"
          
  build-and-release:
    needs: get-manifest-data
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile the kernel
        uses: ophub/amlogic-s9xxx-armbian@main
        with:
          build_target: kernel
          kernel_source: "unifreq"
          kernel_version: ${{ needs.get-manifest-data.outputs.kernel_version }}
          kernel_auto: false
          kernel_package: "all"
          kernel_toolchain: "gcc"
          kernel_sign: "-ophub"
          kernel_config: "kernel-config/release/general"
          compress_format: "xz"

      - name: Upload Kernel to Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.release_version }}
          artifacts: "./output/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
